name: Android Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Setup legacy Android SDK
      run: |
        # 下载兼容 JDK 11 的旧版 Android SDK
        wget https://dl.google.com/android/repository/commandlinetools-linux-8092744_latest.zip
        mkdir -p android-sdk/cmdline-tools
        unzip commandlinetools-linux-8092744_latest.zip -d android-sdk/cmdline-tools/
        mv android-sdk/cmdline-tools/cmdline-tools android-sdk/cmdline-tools/latest
        
        echo "ANDROID_HOME=$GITHUB_WORKSPACE/android-sdk" >> $GITHUB_ENV
        echo "$GITHUB_WORKSPACE/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
    
    - name: Accept licenses
      run: |
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
    
    - name: Install components
      run: |
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-31" "build-tools;31.0.0"
    
    - name: Build
      run: |
        chmod +x ./gradlew
        ./gradlew assembleDebug
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: VCAMSX-Legacy
        path: app/build/outputs/apk/debug/*.apk
