name: Android Build

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 11  # 改为 JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'  # 降级到 JDK 11
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
      
    - name: Build with Gradle
      run: |
        ./gradlew assembleDebug
        
    - name: Upload APK artifacts
      uses: actions/upload-artifact@v4
      with:
        name: app-apks
        path: app/build/outputs/apk/debug/*.apk
